{
 "title": "Restic Exporter",
 "description": "Restic statistics dashboard",
 "tags": [ "system" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repository Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_check_success" }
   ]
  },
  {
   "title": "Repository Locks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_locks_total" }
   ]
  },
  {
   "title": "Repository total size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_size_total" }
   ]
  },
  {
   "title": "Repository total snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_snapshots_total" }
   ]
  },
  {
   "title": "Last backup",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "restic_backup_timestamp * 1000", "legendFormat": "{{client_hostname}}" },
    {
     "expr": "time() - restic_backup_timestamp",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Total snapshot count",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "restic_backup_snapshots_total", "legendFormat": "{{client_hostname}}" }
   ]
  },
  {
   "title": "Total backup size & files",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "restic_backup_size_total", "legendFormat": "{{client_hostname}}" },
    { "expr": "restic_backup_files_total", "legendFormat": "{{client_hostname}}" }
   ]
  },
  {
   "title": "Total backup size",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_backup_size_total", "legendFormat": "{{client_hostname}}" }
   ]
  },
  {
   "title": "Total backup size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_size_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Total backup files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_files_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Total snapshot count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_snapshots_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Repository total size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_size_total" }
   ]
  },
  {
   "title": "Repository total uncompressed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_uncompressed_size_total" }
   ]
  },
  {
   "title": "Repository compression ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_compression_ratio" }
   ]
  },
  {
   "title": "Repository total snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_snapshots_total" }
   ]
  },
  {
   "title": "Repository total blobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_blob_count_total" }
   ]
  },
  {
   "title": "Exporter scrape duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_scrape_duration_seconds" }
   ]
  },
  {
   "title": "Repository total size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "restic_size_total", "legendFormat": "Compressed size" },
    { "expr": "restic_uncompressed_size_total", "legendFormat": "Uncompressed size" }
   ]
  },
  {
   "title": "Backup total size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_size_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup data added (last backup)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_data_added_bytes)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup total files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_files_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup files new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_files_new)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup files changed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_files_changed)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup files unmodified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_files_unmodified)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup directories new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_dirs_new)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup directories changed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_dirs_changed)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup directories unmodified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_dirs_unmodified)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Backup duration (time measured by restic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(client_hostname,client_username) (restic_backup_duration_seconds)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  }
 ]
}